# Este arquivo foi limpo como parte da refatoração para uma arquitetura "Frontend-Only".
# O backend Python/FastAPI e seus serviços de suporte foram descontinuados.
# A aplicação agora é uma SPA (Single Page Application) autônoma que
# executa toda a lógica no cliente (navegador).
